name = "FreydCategoriesForCAP"
uuid = "cec356e3-7627-4f73-8308-af32cbf46c2b"
authors = ["Sebastian Posur <sebastian.posur@uni-muenster.de>", "Martin Bies <martin.bies@alumni.uni-heidelberg.de>", "Fabian Zickgraf <f.zickgraf@dashdos.com>"]
version = "0.1.2"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
LinearAlgebraForCAP = "3dc4824f-14ac-4ab7-8a60-75dbcd4a9d60"
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
MonoidalCategories = "bfd98c86-782f-4b94-909f-74167f1eb613"

[weakdeps]
CartesianCategories = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"
FinSetsForCAP = "0a079e9b-4bc2-44fe-a89b-7607e4464786"
Toposes = "36a15fe6-6211-457f-8fdb-aa2e0d2f3052"

[extensions]
FreydCategoriesForCAPFinSetsForCAPExtension = ["CartesianCategories", "Toposes", "FinSetsForCAP"]

[compat]
CAP = "0.3, 0.4"
CartesianCategories = "0.1"
FinSetsForCAP = "0.1"
LinearAlgebraForCAP = "0.1"
MatricesForHomalg = "0.1"
MonoidalCategories = "0.1"
Toposes = "0.1"
julia = "1.11"

[extras]
CartesianCategories = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FinSetsForCAP = "0a079e9b-4bc2-44fe-a89b-7607e4464786"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Toposes = "36a15fe6-6211-457f-8fdb-aa2e0d2f3052"

[targets]
test = ["Test", "Documenter", "CartesianCategories", "Toposes", "FinSetsForCAP"]
